CREATE TABLE gallery(
    ID SERIAL PRIMARY KEY,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SHOW BOOLEAN NOT NULL,
    RANK INT
);

CREATE TABLE photo(
    ID SERIAL PRIMARY KEY,
    GALLERYID INT NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    FILENAME TEXT,
    THUMBFILENAME TEXT,
    RANK INT,
    IMAGE BYTEA,
    THUMB BYTEA
);

CREATE TABLE admin_user(
    ID SERIAL PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    PASSWORDHASH BYTEA NOT NULL,
    SALT BYTEA NOT NULL
);